@api = http://localhost:8000/api

GET {{api}}/items/emunoz1

###
POST {{api}}/items/emunoz1
Content-Type: application/json

{
    "text": "Im here",
    "done": false
}

###
PUT {{api}}/items/emunoz1/65f07929a5b60656558a811e
Content-Type: application/json

{
    "text": "updated!",
    "done": true
}

###
DELETE {{api}}/items/emunoz1/65f07929a5b60656558a811e
