@api = http://localhost:8000/api
@Q_id = 65fcda082139e33bdaf57750

@A_id = 65fcda4b2b68a2e4d83a16ef

GET {{api}}/questions

###
POST {{api}}/questions
Content-type: application/json

{
    "summary": "Second question",
    "contents": "What's a dog",
    "author": "esteban4",
    "likeCount": 1
}

###
GET {{api}}/questions/{{Q_id}} 

###
PUT {{api}}/questions/{{Q_id}} 
Content-Type: application/json 

{
    "summary": "Updated Question",
    "contents": "WORKING!",
    "author": "Mirna24",
    "likeCount": 1
}

###
POST {{api}}/questions/{{Q_id}}/answers
Content-Type: application/json

{
    "contents": "Also the turtle",
    "author": "Estea28",
    "likeCount": 1
}

###
GET {{api}}/answers/{{A_id}}

###
PUT {{api}}/answers/{{A_id}}
Content-Type: application/json

{
    "contents": "Cats are cute",
    "author": "Estebna18",
    "likeCount": 1
}

###
GET {{api}}/questions/{{Q_id}}/answers

