@api = http://localhost:8000/api

GET {{api}}/questions

###
POST {{api}}/questions
Content-type: application/json

{
    "summary": "find me test",
    "contents": "question",
    "author": "esteban24",
    "likeCount": 1
}

###
GET {{api}}/questions/65fb27431bd8807cf1ba17b9 

###
PUT {{api}}/questions/65fa5898baf93db8f15c8804
Content-Type: application/json 

{
    "_id": "65fa5898baf93db8f15c8804",
    "summary": "hola amigos, Como estan",
    "contents": "new question",
    "author": "Mirna",
    "likeCount": 1,
    "created": "2024-03-20T03:31:36.961Z",
    "edited": "2024-03-20T03:31:36.961Z",
    "__v": 0
  }