@api = http://localhost:8000/api
@Q_id = 6602422fe2c0c6f26a877cb8
@A_id = 6601ff76720b773747227b7f
@username = estebanAdmin
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0YXouaGFyZGluZy5lZHUiLCJzdWIiOiJlc3RlYmFuQWRtaW4iLCJhdWQiOiJ0ZXN0Iiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzExNDE0MzkwLCJleHAiOjE3MTQwMDYzOTB9.UJhySuFd423lNMUoFBjcnw0TUb7qjw7au8d3INuMV07hoBNRIsT-a51U-LV7p1uK-GY5w4KxccvBy3u1v1gHejU8rK-ms8Pe3NNac91osRiL-2AHC8pQBAGCQ8qhSreIVIqWRDdrRmSClDJgA89MyxQDCCrR3hKQwA0xNnsj0xwgJnHA9haOmwIaLpQET9kH7GMKex1Rj1zPvXV8dyLM1gpq8SH4y6NU8AU8V46KqArd32B8u6YlEbY-FQ8LAEf7I_2CrwCJRyIMHwoMQZmc6eS2J6whPdxz0sI6gIht5Z1WlMygECTJhxcMXF-iCbxM9cAeMrxmOj-Hj5AOv_M4iQ



GET {{api}}/questions
Authorization: Bearer {{token}}

#WHAT TO DO WITH LIKE COUNT?

###
POST {{api}}/questions
Content-type: application/json
Authorization: Bearer {{token}}

{
    "summary":  "New Authenticated Question",
    "contents": "I should have unlimented power",
    "author": "EstebanAdmin"
}

###
GET {{api}}/questions/{{Q_id}} 
Authorization: Bearer {{token}}

###
PUT {{api}}/questions/{{Q_id}} 
Content-Type: application/json 

{
    "summary": "Updated Question",
    "contents": "WORKING!",
    "author": "Mirna24",
    "likeCount": 0
}

#----------------ANSWER SECTION------------------------------

###
POST {{api}}/questions/{{Q_id}}/answers
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "contents": "Coccoroco",
    "author": "chickenNoodle",
    "likeCount": 0
}

###
GET {{api}}/answers/{{A_id}}

###
PUT {{api}}/answers/{{A_id}}
Content-Type: application/json

{
    "contents": "Cats are cute",
    "author": "Estebna18",
    "likeCount": 0
}

###
GET {{api}}/questions/{{Q_id}}/answers

#----------------LIKES SECTION------------------------------

###
GET {{api}}/likes/{{Q_id}}
Authorization: Bearer {{token}}

###
GET {{api}}/likes/{{Q_id}}/{{username}}
Authorization: Bearer {{token}}

###
POST {{api}}/likes/{{Q_id}}/steban22
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE {{api}}/likes/{{Q_id}}/steban22
Authorization: Bearer {{token}}


